// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk4TUGehWyqMhVfbSSFp6VuJ3Inm1yUvU',
    appId: '1:367146511718:web:e7e71b19793fbb5a9eaca7',
    messagingSenderId: '367146511718',
    projectId: 'fast-it-id-feb06',
    authDomain: 'fast-it-id-feb06.firebaseapp.com',
    storageBucket: 'fast-it-id-feb06.appspot.com',
    measurementId: 'G-58GZWZGG7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCillYcZcm2VUPBNLB8LVJ2_hBeqq6QZXY',
    appId: '1:367146511718:android:d753eaf984e514979eaca7',
    messagingSenderId: '367146511718',
    projectId: 'fast-it-id-feb06',
    storageBucket: 'fast-it-id-feb06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSaL2mNcDSXTYbY20Fb_NPxUBQtKy7VY',
    appId: '1:367146511718:ios:44394b05e25f18939eaca7',
    messagingSenderId: '367146511718',
    projectId: 'fast-it-id-feb06',
    storageBucket: 'fast-it-id-feb06.appspot.com',
    iosBundleId: 'com.example.fastIt2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiSaL2mNcDSXTYbY20Fb_NPxUBQtKy7VY',
    appId: '1:367146511718:ios:85d86ca0f05927139eaca7',
    messagingSenderId: '367146511718',
    projectId: 'fast-it-id-feb06',
    storageBucket: 'fast-it-id-feb06.appspot.com',
    iosBundleId: 'com.example.fastIt2.RunnerTests',
  );
}
